name: todo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.1
  email_validator: ^2.1.17
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^3.0.1
  lottie: ^2.6.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
